name: CI/CD Deployment to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Build Docker image
        run: docker build -t musait_hr_bot:latest .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Tag and push Docker image
        run: |
          docker tag musait_hr_bot:latest ghcr.io/mirshodnasilloyev/musait_hr_bot:latest
          docker push ghcr.io/mirshodnasilloyev/musait_hr_bot:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy Docker container to remote server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << EOF
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull ghcr.io/${{ github.repository }}/musait_hr_bot:latest
            docker stop musait_hr_bot || true
            docker rm musait_hr_bot || true
            docker run -d --name musait_hr_bot \
              -e TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} \
              -p 80:80 \
              ghcr.io/${{ github.repository }}/musait_hr_bot:latest
          EOF
