name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download code
        uses: actions/checkout@v3

      - name: Go settings
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Create docker image
        run: docker build -t musaitHrMgBotGo:latest .

      - name: Enter into Github Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add tag into docker image
        run: |
          docker tag musaitHrMgBotGo:latest ghcr.io/${{ github.repository }}/musaitHrMgBotGo:latest
          docker push ghcr.io/${{ github.repository }}/musaitHrMgBotGo:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploying a Docker container to a remote server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: |
          # Create docker image and restart server
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << EOF
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull ghcr.io/${{ github.repository }}/musaitHrMgBotGo:latest
            docker stop musaitHrMgBotGo || true
            docker rm musaitHrMgBotGo || true
            docker run -d --name musaitHrMgBotGo \
              -e TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} \
              ghcr.io/${{ github.repository }}/musaitHrMgBotGo:latest
          EOF
